name: Scrape SkymoviesHD

on:
  workflow_dispatch:
    inputs:
      max_pages:
        description: 'Max pages per category'
        required: false
        default: '20'

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scraper.py --max-pages "${{ github.event.inputs.max_pages || '20' }}"

      - name: Upload Excel artifact
        uses: actions/upload-artifact@v4
        with:
          name: skymovies-excel
          path: "*.xlsx"
          if-no-files-found: error
          retention-days: 7
